version: '2'
services:
  redis-cluster:
    image: scvgoe/redis-cluster
    environment:
     IP: ${REDIS_CLUSTER_IP}
     SENTINEL: ${REDIS_USE_SENTINEL}
     STANDALONE: ${REDIS_USE_STANDALONE}
    build:
      context: .
      args:
        redis_version: '5.0.3'
    hostname: server
    ports:
      - '6379-6386:6379-6386'
      - '5000-5002:5000-5002'
